name: Build/Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  build-deploy-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Use Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"
          cache-dependency-path: |
            SpotifyAPI.Docs/pnpm-lock.yaml
      - name: Setup GitHub Deploy SSH Key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.GH_DEPLOY_SSH_KEY }}
      - name: Build & Deploy Documentation
        run: ./SpotifyAPI.Docs/docs.sh
